default: &default
  DATABASE_HOST: localhost
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'postgres'
  WEB_HOST: 'localhost'
  QINIU_AK: 'KoHsIl4VZfafoyNw8K--EBUP91ftuL4KMyuFNIpu'
  QINIU_SK: 'k1_Kc1VUuWZ9iqEoFB_neuW8rl2OUEKktjEMaP35'
  FILE_NAME: 'apps.xls'

development:
  <<: *default
  HOSTNAME: 'http://localhost:3032'
  QINIU_BUCKET: 'padagogy-dev'
  QINIU_BUCKET_DOMAIN: 'p8hxee5ff.bkt.clouddn.com'

test:
  <<: *default
  HOSTNAME: 'http://localhost:3032'

staging:
  <<: *default
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'postgres'
  SECRET_KEY_BASE: 'aa415858c2d1301b8fa0b31c4276e7f5e7b1bb9a16ad4b638d2606ae13eceb430dcdc73eed047a2aa41513e10d18ddbe897269c428ebc730b1b6570a04fc6751'

production:
  <<: *default
  WEB_HOST: ''
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'postgres'
  SECRET_KEY_BASE: 'aa415858c2d1301b8fa0b31c4276e7f5e7b1bb9a16ad4b638d2606ae13eceb430dcdc73eed047a2aa41513e10d18ddbe897269c428ebc730b1b6570a04fc6710'

